[package]
name = "fye_client"
version.workspace = true
authors.workspace = true
edition = "2021"

[[bin]]
name = "fye"
path = "src/main.rs"

[dependencies]
fuser = { version = "0.14.0", default-features = false }
libc = "0.2.158"
